name: ✨ Enhancement
description: Suggest an improvement of an existing feature
title: "[Enhancement] "
labels: [ "type: enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > Kindly search for similar issues before creating a new one to help us keep the tracker organized.
  - type: textarea
    attributes:
      label: Current Behavior
      description: What problem or limitation have you encountered?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Behavior
      description: What new behavior would you like to see?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use Case
      description: How would the change improve the user experience or performance of the action?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: How could the enhancement be implemented?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: Please provide any relevant details, references, or examples.
    validations:
      required: false
