name: Label

on:
  pull_request:
    types: [ labeled, unlabeled ]

jobs:
  # to resolve workflow syntax limitation (jobs.<job_id>.if)
  preprocess:
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ join(github.event.pull_request.labels.*.name, ', ') }}
    steps:
      - name: Set exit code
        run: exit 0

  block-by-no-merge:
    needs: [ preprocess ]
    if: ${{ contains(needs.preprocess.outputs.labels, 'no merge') }}
    runs-on: ubuntu-latest
    steps:
      - name: |
          Fail the status check if the pull request is labeled as 'no merge'
        run: |
          echo "This PR is labeled as 'no merge'. All tests must pass before merging."
          exit 1

  block-by-feedback-required:
    needs: [ preprocess ]
    if: ${{ contains(needs.preprocess.outputs.labels, 'feedback required') }}
    runs-on: ubuntu-latest
    steps:
      - name: |
          Fail the status check if the pull request is labeled as 'status: feedback required'
        run: |
          echo "This PR is labeled as 'status: feedback required'. Additional information is needed before proceeding."
          exit 1

  block-by-review-required:
    needs: [ preprocess ]
    if: ${{ contains(needs.preprocess.outputs.labels, 'review required') }}
    runs-on: ubuntu-latest
    steps:
      - name: |
          Fail the status check if the pull request is labeled as 'status: review required'
        run: |
          echo "This PR is labeled as 'status: review required'. Approval from reviewers is needed prior to merging."
          exit 1
