name: Pull Request

on:
  pull_request:
    branches:
      - "main"
      - "preview"
      - "releases/**"
    paths:
      - "action.yml"
      - "entrypoint/**/*.sh"
      - ".github/workflows/**/*.yml"

jobs:
  label-no-merge:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Add 'no merge' label to the updated pull request
        run: |
          STATUS_CODE=$(
            curl -s -L -X POST --oauth2-bearer ${{ secrets.ACTION_TEST_TOKEN }} \
            -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
            -w "%{response_code}\n" -o /dev/null \
            --json '{"labels": ["no merge"]}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels"
          )
          echo "Status: ${STATUS_CODE}"
          if [ ${STATUS_CODE} -ne 200 ]; then exit 1; fi

  run-test:
    permissions:
      contents: write
    needs: [ label-no-merge ]
    uses: ./.github/workflows/integration-test.yml
    secrets: inherit
