name: Release

on:
  release:
    types: [ released ]

jobs:
  tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Get the bot profile
        id: profile
        uses: octokit/request-action@v2.x
        with:
          route: GET /users/{username}
          username: "github-actions[bot]"
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upsert the major version tag reference
        id: tag
        run: |
          MAJOR_VERSION=$(echo ${{ github.ref_name }} | cut -d "." -f 1)
          echo "MAJOR_VERSION: ${MAJOR_VERSION}"
          git config user.name "${{ env.USER_NAME }}"
          git config user.email "${{ env.USER_ID }}+${{ env.USER_NAME }}@users.noreply.github.com"
          git tag -f "${MAJOR_VERSION}" ${{ github.sha }}
          git push -f origin "${MAJOR_VERSION}"
        env:
          USER_ID: ${{ fromJson(steps.profile.outputs.data).id }}
          USER_NAME: ${{ fromJson(steps.profile.outputs.data).login }}

  notify:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cynthiachanky/discord-notification-action@v1
        with:
          webhook_url: ${{ secrets.CHANGELOG_CHANNEL }}
          post_as: "action"
