name: Daily Scheduler

on:
  schedule:
    - cron: "30 18 * * *" # 0230 HKT every day

jobs:
  stale:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 7
          days-before-issue-close: -1
          stale-issue-message: "This issue is stale because it has been open 30 days with no activity."
          stale-pr-message: "This pull request is stale because it has been open 30 days with no activity. Please respond to this comment or this pull request will be closed in 7 days."
          close-pr-message: "This pull request was closed because it has been stale 7 days with no activity."
          stale-issue-label: "status: stale"
          stale-pr-label: "status: stale"
          exempt-issue-labels: "status: review required"
          exempt-pr-labels: "status: review required"
          ascending: true
